name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.js quraşdırmaq
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Newman quraşdırmaq
        run: npm install -g newman
      - name: Reporter quraşdırmaq
        run: npm install -g newman-reporter-htmlextra
      - name: Postman kolleksiyasını HTML Extra hesabatı ilə işə salmaq
        run: |
          newman run "Simple Books API.postman_collection.json" \
          -e "simple_books.postman_environment.json" \
          -r htmlextra --reporter-htmlextra-export newman/report.html
      - name: HTML hesabatını yükləmək
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Postman-HTML-Report
          path: newman/report.html
      - name: HTML hesabatını repoya push etmək
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add newman/report.html
          git commit -m "Add Postman test report"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ZeynabMehdiyeva/newman_api_books.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
