name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Newman
        run: npm install -g newman
      - name: Install Reporter
        run: npm install -g newman-reporter-htmlextra
      - name: Run Postman Collection with HTML Extra Report
        run: |
         newman run "./newman/Simple Books API.postman_collection.json" \
         -e "./newman/simple_books.postman_environment.json" \
         -r htmlextra --reporter-htmlextra-export newman/report.html
